# Generated by Django 5.0.6 on 2024-06-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('cookie_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('flavour', models.CharField(max_length=30)),
            ],
        ),
    ]
