# Generated by Django 5.0.6 on 2024-06-03 07:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_drf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
