# Generated by Django 5.0.6 on 2024-06-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_drf', '0002_alter_user_joined_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posts',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='captain',
            new_name='captian',
        ),
    ]
