# Generated by Django 5.0.6 on 2024-06-03 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_drf', '0003_rename_post_posts_rename_user_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='joined_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
