# Generated by Django 5.0.6 on 2024-06-17 13:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=30)),
                ('client_id', models.CharField(max_length=10)),
                ('client_secret', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Interns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('college', models.CharField(max_length=70)),
                ('graduation_year', models.IntegerField()),
                ('passed', models.BooleanField(null=True)),
            ],
        ),
    ]
