# Generated by Django 5.0.6 on 2024-05-25 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0002_alter_books_published_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='books',
            unique_together={('author', 'title', 'published_date')},
        ),
    ]
