# Generated by Django 5.0.6 on 2024-05-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data1', '0003_alter_books_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='time_diff',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='time_taken',
            field=models.DateTimeField(null=True),
        ),
    ]
